[time]
disabled=false
format = 'ğŸ•™[\[ $time \]]($style) '

[directory]
truncation_length = 10
truncate_to_repo = false

[aws]
disabled=true

[gcloud]
disabled=true

[git_status]
modified = "ğŸ“"
untracked = "â“"

